version: 3.8
services:
  build: ./server
  ports:
    - "5000:5000"
  environment:
    - NODE_ENV=development
    - POSTGRES_URI=TODO
  depends_on:
    - postgres

  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - server

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/data/postgres

  volumes:
    postgres_data:
