version: 3.8
services:
  build: ./server
  ports:
    - "${SERVER_PORT}:${SERVER_PORT}"
  environment:
    - NODE_ENV=development
    - POSTGRES_URI=TODO
  depends_on:
    - db

  client:
    build: ./client
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    environment:
      - NODE_ENV=development
    depends_on:
      - server

  db:
    image: postgres:13
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_SUPER_USER}
      - POSTGRES_PASSWORD=${DB_SUPER_USER_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/data/postgres

  volumes:
    postgres_data:
